### ISSUE TITLE
angular-ui/ui-tinymce setup method in tinymceOptions breaks model binding

### ISSUE THREAD

**Issue by polojko** [angular-ui/ui-tinymce#112]
I want to add a custom button to the tinymce toolbar, and added a setup function to tinymceOptions as discribed in the docs:

$scope.tinymceOptions = {
     setup: function (editor) {
               editor.addButton('myMethod', { //myCode }
     },
    //more options
}

<textarea ui-tinymce="tinymceOptions" ng-model="model.content"></textarea>

Adding the setup function breaks the binding with the model. Content added to the editor is not synced to the model and vice-versa.

Are there known issues with this approach? If so, what would be the other way to add custom buttons, without breaking binding?

Tnx;

**Comment by joshuakon** [comment]
this doesn't work for me. the attrs object isn't defined. if I remove the mode and elements items, the editor doesn't load.

**Comment by helmutkian** [comment]
If you do not need to handle events that occur before the ``'init'`` event, then until the issue with ``setup`` is resolved, you could use ``init_instance_callback`` instead.

So replace

````
{
   // ...
   setup: function (ed) {
       ed
         .on('init', function () { alert('init!'); })
         .on('blur', function () { alert('blurred!'); });
   }
}
````

with

````
{
   // ...
   init_instance_callback: function (ed) {
       alert('init!');
       ed.on('blur', function () { alert('blurred!'); });
   }
}
````

**Comment by minutephp** [comment]
This seems to work for now:

inside tinymce.js

```Javascript
if (expression.custom_setup) {
    scope.$eval(function () {
          expression.custom_setup(ed)
     });
     delete expression.custom_setup;
}
```

inside your_code.js
```Javascript

$scope.tinymceOptions = {
//...
custom_setup: function(editor) { /* setup */ }
}
```

**Comment by daynejones** [comment]
Can confirm this is an issue for me as well.

**Comment by thatguyyoulove** [comment]
This was resolved with ae37bb9dd9e1094b5a2379bb4a63e35209f14622, however the tagging is currently messed up and version 0.0.5 does not currently resolve to the correct version 0.0.5 tag. 

Recommendation is to download the .zip of the real v.0.0.5 and use that in the interim.
https://github.com/angular-ui/ui-tinymce/archive/v0.0.5.zip

**Comment by rbecheras** [comment]
Ok @thatguyyoulove it cool, but why there is no new tag 0.0.6 tag ?
This issue is important !

**Comment by thatguyyoulove** [comment]
Comment on #127 to get support for having it fixed please.

**Comment by wesleycho** [comment]
I believe this is now fixed - I have removed the broken 0.0.5 tag and released 0.0.6.

I do however think that the api is a little awkward for extending the setup function - I am open to any ideas on a better way to extend the logic in the existing callbacks, in the event the user wants custom behavior to happen, if it is desired. If anyone is interested, feel free to open a new issue on this.

**Comment by webdev67** [comment]
It still happens. Using the    init_instance_callback as @helmutkian  suggested does not work if you are adding a new button . It works for the context menu surprisingly..

**Comment by webdev67** [comment]
Just FYI - i solved the issue of not being able to add the button via creating a new plugin - and injecting that in the tinymce options. I also passed the $rootScope, $scope and other angular requirements to the plugin via this.PluginManager.$rootScope = $rootScope from within the init_instance_callback function in the $scope.tinymceOptions in the controller.

**Comment by asanthoshkumar** [comment]
Take the @mangreen code, It fixed couple of issues for me.
1) Allows me to add custom button.
2) When inline=true two way binding not works without this fix for me.

**Comment by andreyluiz** [comment]
Not only in this case. In my approach I need to do stuff in the init. And I can't setup this because the entire model binding is lost (setup function extends over the original one in the directive).

**Comment by deeg** [comment]
Will a new version be put out with the fix by @mangreen?

**Comment by yaegerbomb** [comment]
Since updating to the latest version of Tiny I had to do the following to get my angular buttons to work:

` $scope.tinymceOptions = { `
       `       external_plugins: { "custom-button": "/scripts/libraries/ui-tiny/plugin.js" }`
       `       init_instance_callback: function (ed) {`
              `      ed.$scope = $scope;`
        `      },`
        `       toolbar: "custom-plugin"`
 ` }`

In the plugin.js folder it was just a normal ed.addButton function.
